# Generated by Django 3.2.9 on 2021-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('services', models.CharField(choices=[('Option 1', 'Graphic Design'), ('Option 2', 'Photography'), ('Option 3', 'Art Project')], max_length=200)),
            ],
        ),
    ]
